args=commandArgs(trailingOnly = TRUE)
snp.list.file=args[1]  ## this is the .nopred file generated by plink --score function 
predictor.file=args[2] ## this is the predictor file you used to profile PGS.

library(data.table)
pred = data.frame(fread(predictor.file))
snp.list = read.table(snp.list.file)

pred.subset = pred[!pred$Name %in% snp.list$V2,]
x = round(100 * sum(pred.subset$VarExplained) / sum(pred$VarExplained), digits = 2)
y = formatC(sum(pred$VarExplained), format="e", digits =2 ) 

print(paste0("Genetic variation of this trait is ", y, "." ))

print(paste0("The ",  (nrow(pred) - nrow(snp.list) )  , " SNPs in the target data can capture ", x , "% of it." ))





